CREATE DATABASE IF NOT EXISTS farmAfrica;

USE farmAfrica;
--users TABLE (not final)
CREATE TABLE IF NOT EXISTS users(
	userID INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	userName VARCHAR(30) NOT NULL UNIQUE,
	firstName VARCHAR(45) NOT NULL,
	lastName VARCHAR(45) NOT NULL,
	emailAddress VARCHAR(100) DEFAULT NULL UNIQUE,
	phoneNumber VARCHAR(15) DEFAULT NULL,
	status INT(11) UNSIGNED NOT NULL,
	dateCreated DATETIME NOT NULL,
	createdBy INT(11) UNSIGNED NOT NULL,
	dateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	modifiedBy INT(11) UNSIGNED NOT NULL
) ENGINE=InnoDB;

--statusTypes TABLE
CREATE TABLE IF NOT EXISTS statusTypes(
	statusTypeID INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	statusTypeName VARCHAR(30) NOT NULL UNIQUE,
	status INT(11) UNSIGNED NOT NULL,
	dateCreated DATETIME NOT NULL,
	createdBy INT(11) UNSIGNED NOT NULL,
	dateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	modifiedBy INT(11) UNSIGNED NOT NULL	
) ENGINE=InnoDB;

--statusCategories TABLE
CREATE TABLE IF NOT EXISTS statusCategories(
	statusCategoryID INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	categoryName VARCHAR(30) NOT NULL UNIQUE,
	status INT(11) UNSIGNED NOT NULL,
	dateCreated DATETIME NOT NULL,
	createdBy INT(11) UNSIGNED NOT NULL,
	dateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	modifiedBy INT(11) UNSIGNED NOT NULL	
) ENGINE=InnoDB;

--statusCodes TABLE
CREATE TABLE IF NOT EXISTS statusCodes(
	statusID INT(11) UNSIGNED NOT NULL PRIMARY KEY,
	statusDesc VARCHAR(100) NOT NULL UNIQUE,
	description TEXT DEFAULT NULL,
	statusTypeID INT(11) UNSIGNED NOT NULL,
	statusCategoryID INT(11) UNSIGNED NOT NULL,
	dateCreated DATETIME NOT NULL,
	createdBy INT(11) UNSIGNED NOT NULL,
	dateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	modifiedBy INT(11) UNSIGNED NOT NULL,
	CONSTRAINT FOREIGN KEY (`statusTypeID`) REFERENCES `statusTypes`(`statusTypeID`),
	CONSTRAINT FOREIGN KEY (`statusCategoryID`) REFERENCES `statusCategories`(`statusCategoryID`)
) ENGINE=InnoDB;

--groups TABLE
CREATE TABLE IF NOT EXISTS groups(
	groupID INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	groupName VARCHAR(45) NOT NULL UNIQUE,
	description VARCHAR(200) NOT NULL,
	status INT(11) UNSIGNED NOT NULL,
	dateCreated DATETIME NOT NULL,
	createdBy INT(11) UNSIGNED NOT NULL,
	dateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	modifiedBy INT(11) UNSIGNED NOT NULL	
) ENGINE=InnoDB;

--userGroupMappings TABLE
CREATE TABLE IF NOT EXISTS userGroupMappings(
	userGroupMappingID INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	userID INT(11) UNSIGNED NOT NULL,
	groupID INT(11) UNSIGNED NOT NULL,
	status INT(11) UNSIGNED NOT NULL,
	dateCreated DATETIME NOT NULL,
	createdBy INT(11) UNSIGNED NOT NULL,
	dateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	modifiedBy INT(11) UNSIGNED NOT NULL,
	CONSTRAINT FOREIGN KEY (`userID`) REFERENCES `users`(`userID`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT FOREIGN KEY (`groupID`) REFERENCES `groups`(`groupID`) ON UPDATE NO ACTION ON DELETE NO ACTION
) ENGINE=InnoDB;

--modules TABLE
CREATE TABLE IF NOT EXISTS modules(
	moduleID INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	moduleName VARCHAR(45) NOT NULL UNIQUE,
	description VARCHAR(200) NOT NULL,
	status INT(11) UNSIGNED NOT NULL,
	dateCreated DATETIME NOT NULL,
	createdBy INT(11) UNSIGNED NOT NULL,
	dateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	modifiedBy INT(11) UNSIGNED NOT NULL
) ENGINE = InnoDB;

--entityActions TABLE
CREATE TABLE IF NOT EXISTS entityActions(
	entityActionID INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	entityActionName VARCHAR(20) NOT NULL UNIQUE,
	description VARCHAR(200) NOT NULL,
	status INT(11) UNSIGNED NOT NULL,
	dateCreated DATETIME NOT NULL,
	createdBy INT(11) UNSIGNED NOT NULL,
	dateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	modifiedBy INT(11) UNSIGNED NOT NULL
) ENGINE = InnoDB;

--moduleActions TABLE
CREATE TABLE IF NOT EXISTS moduleActions(
	moduleActionID INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	moduleID INT(11) UNSIGNED NOT NULL,
	entityActionID INT(11) UNSIGNED NOT NULL,
	status INT(11) UNSIGNED NOT NULL,
	dateCreated DATETIME NOT NULL,
	createdBy INT(11) UNSIGNED NOT NULL,
	dateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	modifiedBy INT(11) UNSIGNED NOT NULL,
	CONSTRAINT `moduleAction` UNIQUE KEY (`moduleID`, `entityActionID`),
	CONSTRAINT FOREIGN KEY (`moduleID`) REFERENCES `modules`(`moduleID`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT FOREIGN KEY (`entityActionID`) REFERENCES `entityActions`(`entityActionID`) ON UPDATE NO ACTION ON DELETE NO ACTION
) ENGINE=InnoDB;

--permissions TABLE
CREATE TABLE IF NOT EXISTS permissions(
	permissionID INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	moduleActionID INT(11) UNSIGNED NOT NULL,
	groupID INT(11) UNSIGNED NOT NULL,
	status INT(11) UNSIGNED NOT NULL,
	dateCreated DATETIME NOT NULL,
	createdBy INT(11) UNSIGNED NOT NULL,
	dateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	modifiedBy INT(11) UNSIGNED NOT NULL,
	CONSTRAINT `permission` UNIQUE KEY (`moduleActionID`, `groupID`),
	CONSTRAINT FOREIGN KEY (`moduleActionID`) REFERENCES `moduleActions`(`moduleActionID`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT FOREIGN KEY (`groupID`) REFERENCES `groups`(`groupID`) ON UPDATE NO ACTION ON DELETE NO ACTION
) ENGINE=InnoDB;

--productTypes TABLE
CREATE TABLE IF NOT EXISTS productTypes(
	productTypeID INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	productTypeName VARCHAR(45) UNIQUE NOT NULL,
	status INT(11) UNSIGNED NOT NULL,
	dateCreated DATETIME NOT NULL,
	createdBy INT(11) UNSIGNED NOT NULL,
	dateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	modifiedBy INT(11) UNSIGNED NOT NULL
) ENGINE=InnoDB;

--products TABLE
CREATE TABLE IF NOT EXISTS products(
	productID INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	productName VARCHAR(45) UNIQUE NOT NULL,
	description VARCHAR(200) NOT NULL,
	productTypeID INT(11) UNSIGNED NOT NULL,
	status INT(11) UNSIGNED NOT NULL,
	dateCreated DATETIME NOT NULL,
	createdBy INT(11) UNSIGNED NOT NULL,
	dateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	modifiedBy INT(11) UNSIGNED NOT NULL,
	CONSTRAINT FOREIGN KEY (`productTypeID`) REFERENCES `productTypes`(`productTypeID`) ON UPDATE NO ACTION ON DELETE NO ACTION
) ENGINE=InnoDB;

--services TABLE
CREATE TABLE IF NOT EXISTS services(
	serviceID INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	serviceName VARCHAR(45) UNIQUE NOT NULL,
	description VARCHAR(200) NOT NULL,
	status INT(11) UNSIGNED NOT NULL,
	dateCreated DATETIME NOT NULL,
	createdBy INT(11) UNSIGNED NOT NULL,
	dateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	modifiedBy INT(11) UNSIGNED NOT NULL
) ENGINE=InnoDB;

--transactions TABLE
CREATE TABLE IF NOT EXISTS transactions(
	transactionID INT(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	serviceID INT(11) UNSIGNED,
	productID INT(11) UNSIGNED,
	initiatorID INT(11) UNSIGNED,
	receiverID INT(11) UNSIGNED,
	status INT(11) UNSIGNED NOT NULL,
	dateCreated DATETIME NOT NULL,
	createdBy INT(11) UNSIGNED NOT NULL,
	dateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	modifiedBy INT(11) UNSIGNED NOT NULL,
	CONSTRAINT FOREIGN KEY (`serviceID`) REFERENCES `services`(`serviceID`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT FOREIGN KEY (`initiatorID`) REFERENCES `users`(`userID`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT FOREIGN KEY (`receiverID`) REFERENCES `users`(`userID`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT FOREIGN KEY (`productID`) REFERENCES `products`(`productID`) ON UPDATE NO ACTION ON DELETE NO ACTION
) ENGINE=InnoDB;

--userProfiles TABLE
CREATE TABLE IF NOT EXISTS userProfiles(
	userProfileID INT(11) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	userID INT(11) UNSIGNED UNIQUE NOT NULL,
	dateOfBirth DATETIME DEFAULT NULL,
	dateCreated DATETIME NOT NULL,
	createdBy INT(11) UNSIGNED NOT NULL,
	dateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	modifiedBy INT(11) UNSIGNED NOT NULL,
	CONSTRAINT FOREIGN KEY (`userID`) REFERENCES `users`(`userID`) ON UPDATE NO ACTION ON DELETE NO ACTION
) ENGINE=InnoDB;

--notificationTypes TABLE
CREATE TABLE IF NOT EXISTS `notificationTypes` (
  `notificationTypeID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `notificationTypeName` varchar(30) NOT NULL,
  `status` int(11) unsigned NOT NULL,
  `dateCreated` datetime NOT NULL,
  `createdBy` int(11) unsigned NOT NULL,
  `dateModified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modifiedBy` int(11) unsigned NOT NULL,
  PRIMARY KEY (`notificationTypeID`),
  UNIQUE KEY `notificationTypeName` (`notificationTypeName`)
) ENGINE=InnoDB;

--notifications TABLE
CREATE TABLE IF NOT EXISTS `notifications` (
  `notificationID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `notificationTypeID` int(11) unsigned NOT NULL,
  `message` text,
  `destinationAddress` varchar(100) DEFAULT NULL,
  `messageDetails` text DEFAULT NULL,
  `status` int(11) unsigned NOT NULL,
  `dateCreated` datetime NOT NULL,
  `dateModified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `createdBy` int(11) unsigned NOT NULL,
  `modifiedBy` int(11) unsigned NOT NULL,
  PRIMARY KEY (`notificationID`),
  KEY `notificationTypeID` (`notificationTypeID`),
  CONSTRAINT `notifications_ibfk_1` FOREIGN KEY (`notificationTypeID`) REFERENCES `notificationTypes` (`notificationTypeID`)
) ENGINE=InnoDB;

--passwordRequests TABLE
CREATE TABLE IF NOT EXISTS `passwordRequests` (
  `passwordRequestID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `token` varchar(256) NOT NULL,
  `identifier` varchar(150) NOT NULL,
  `status` int(11) unsigned NOT NULL,
  `dateCreated` datetime NOT NULL,
  `createdBy` int(11) unsigned NOT NULL,
  `dateModified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modifiedBy` int(11) unsigned NOT NULL,
  PRIMARY KEY (`passwordRequestID`)
) ENGINE=InnoDB;

--entityStates TABLE
CREATE TABLE IF NOT EXISTS `entityStates` (
  `entityStateID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `entityStateName` varchar(45) NOT NULL,
  `dateCreated` datetime NOT NULL,
  `createdBy` int(11) unsigned NOT NULL,
  `dateModified` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modifiedBy` int(11) unsigned NOT NULL,
  PRIMARY KEY (`entityStateID`),
  UNIQUE KEY `entityStateName_UNIQUE` (`entityStateName`)
) ENGINE=InnoDB;
